### ISSUE TITLE
下载项目后 项目搭建起来后 pc端没问题 h5端报错

### ISSUE THREAD

**Issue by BecksWang** [polyv/live-js-sdk-demo-basic#4]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
Failed to load because no supported source was found.

**Comment by heeroluo** [comment]
PC 端浏览器不支持移动端的视频格式，所以会报错。请用手机打开 H5 端。

**Comment by BecksWang** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr.Luo"<notifications@github.com&gt;; 
发送时间: 2020年11月20日(星期五) 中午1:25
收件人: "polyv/live-js-sdk-demo-basic"<live-js-sdk-demo-basic@noreply.github.com&gt;; 
抄送: "Becks"<651712214@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [polyv/live-js-sdk-demo-basic] 下载项目后 项目搭建起来后 pc端没问题 h5端报错 (#4)





 
PC 端浏览器不支持移动端的视频格式，所以会报错。请用手机打开 H5 端。
